### ISSUE TITLE
Uppgift 01 - 07 - Feedback

### ISSUE THREAD

**Issue by ghost** [DavidEdberg/webb2-01#2]
Uppgift 01. OK.

Uppgift 02. OK. 

Uppgift 03. OK.

Uppgift 04. OK. Jag använde **font-variant: small-caps** för att få till "stora små bokstäver" när jag skapade uppgiften.

Uppgift 05. **Fixa till**. Lägg till lite **word-spacing** också.

Uppgift 06. OK.

Uppgift 07. OK.

**Comment by DavidEdberg** [comment]
Ok
